//! Vectors, computed by the application itself (0019). A card's vector is
//! the embedding of a text **composed from its structure** — tags, dates,
//! origin, typed links both ways, description when there is one — never
//! asked from a human (catalog.md § We write for humans). The
//! composition is the one `tools/vectoriser.py` established on 02/09/2026,
//! word for word: the reference index and the vector of a card generated
//! on the fly must come from the same text and the same model, or "close"
//! stops meaning the same thing everywhere.
//!
//! The model is `paraphrase-multilingual-MiniLM-L12-v2` through fastembed
//! (ONNX Runtime), quantized, 384 dimensions, mean pooling, **truncated at
//! 128 tokens** — the Python default, which fastembed-rs does not share
//! (spike of 09/09/2026: at 512 the richest cards drift to 0.82). Output
//! vectors are unit-norm, which the Python index was not; the whole index
//! is therefore regenerated by `forkstify vectors`, once.

use crate::catalog::Card;
use fastembed::{EmbeddingModel, InitOptions, TextEmbedding};
use std::collections::{BTreeMap, HashMap};
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};

pub const MODEL: &str = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2";
pub const DIMENSIONS: usize = 384;
pub const MAX_LENGTH: usize = 128;

/// Country codes the texts spell out, as `vectoriser.py` does; any other
/// two-letter tag is a country too, kept as its code in capitals.
const COUNTRIES: [(&str, &str); 20] = [
    ("fr", "France"),
    ("uk", "Royaume-Uni"),
    ("us", "États-Unis"),
    ("be", "Belgique"),
    ("de", "Allemagne"),
    ("it", "Italie"),
    ("es", "Espagne"),
    ("ca", "Canada"),
    ("au", "Australie"),
    ("se", "Suède"),
    ("no", "Norvège"),
    ("ie", "Irlande"),
    ("jp", "Japon"),
    ("ml", "Mali"),
    ("et", "Éthiopie"),
    ("in", "Inde"),
    ("cz", "Tchéquie"),
    ("nl", "Pays-Bas"),
    ("ch", "Suisse"),
    ("pt", "Portugal"),
];

/// One sentence per link type, in the card's direction then reversed: a
/// link is carried by one card but holds both ways, only `influence` turns.
fn phrases(kind: &str) -> Option<(&'static str, &'static str)> {
    Some(match kind {
        "member" => ("membres en commun avec {}", "membres en commun avec {}"),
        "collab" => ("a collaboré avec {}", "a collaboré avec {}"),
        "similar" => ("proche de {}", "proche de {}"),
        "family" => ("lié familialement à {}", "lié familialement à {}"),
        "scene" => ("même scène que {}", "même scène que {}"),
        "influence" => ("influencé par {}", "a influencé {}"),
        _ => return None,
    })
}

/// Genres, countries and decades, told apart by their shape.
fn sort_tags(tags: &[String]) -> (Vec<String>, Vec<String>, Vec<String>) {
    let (mut genres, mut countries, mut decades) = (Vec::new(), Vec::new(), Vec::new());
    for tag in tags {
        if let Some((_, name)) = COUNTRIES.iter().find(|(code, _)| *code == tag) {
            countries.push(name.to_string());
        } else if tag.chars().count() == 2 && tag.chars().all(|c| c.is_alphabetic()) {
            countries.push(tag.to_uppercase());
        } else if tag.ends_with('s') && tag.len() > 1 && tag[..tag.len() - 1].chars().all(|c| c.is_ascii_digit()) {
            let digits = &tag[..tag.len() - 1];
            decades.push(format!("années {}", if tag.len() > 3 { digits.to_string() } else { format!("19{digits}") }));
        } else {
            genres.push(tag.replace('-', " "));
        }
    }
    (genres, countries, decades)
}

fn year(date: &str) -> String {
    date.chars().take(4).collect()
}

/// The text of a card, composed from its structure. `cards` is the whole
/// catalog, needed for the names the links point at and for the links that
/// point back — walked in slug order, so the text does not depend on a
/// hash map's mood.
pub fn text_of(slug: &str, card: &Card, cards: &HashMap<String, Card>) -> String {
    let mut sentences = vec![card.name.clone()];
    let (genres, countries, decades) = sort_tags(&card.tags);
    if !genres.is_empty() {
        sentences.push(format!("Genres : {}", genres.join(", ")));
    }
    if !countries.is_empty() {
        sentences.push(format!("Pays : {}", countries.join(", ")));
    }
    if !decades.is_empty() {
        sentences.push(format!("Époque : {}", decades.join(", ")));
    }
    match (card.begin.as_deref().filter(|b| !b.is_empty()), card.end.as_deref().filter(|e| !e.is_empty())) {
        (Some(begin), Some(end)) => sentences.push(format!("Actif de {} à {}", year(begin), year(end))),
        (Some(begin), None) => sentences.push(format!("Actif depuis {}", year(begin))),
        _ => {}
    }
    if let Some(origin) = card.origin.as_deref().filter(|o| !o.is_empty()) {
        sentences.push(format!("Origine : {origin}"));
    }
    let mut relations: Vec<String> = Vec::new();
    for link in &card.links {
        if let (Some(target), Some((forward, _))) = (cards.get(&link.to), phrases(&link.kind)) {
            relations.push(forward.replace("{}", &target.name));
        }
    }
    let others: BTreeMap<&String, &Card> = cards.iter().collect();
    for (_, other) in others {
        for link in &other.links {
            if link.to == slug {
                if let Some((_, back)) = phrases(&link.kind) {
                    relations.push(back.replace("{}", &other.name));
                }
            }
        }
    }
    let mut seen = Vec::new();
    for relation in relations {
        if !seen.contains(&relation) {
            seen.push(relation);
        }
    }
    if !seen.is_empty() {
        sentences.push(seen.join(" ; "));
    }
    if let Some(description) = card.description.as_deref().map(str::trim).filter(|d| !d.is_empty()) {
        sentences.push(description.to_string());
    }
    format!("{}.", sentences.join(". "))
}

/// Where the model lives on this machine: the XDG cache, never the catalog.
pub fn cache_dir() -> PathBuf {
    let base = std::env::var("XDG_CACHE_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from(std::env::var("HOME").unwrap_or_default()).join(".cache"));
    base.join("forkstify").join("fastembed")
}

/// Whether the first embedding will have to fetch the model (241 MB) —
/// worth a word on screen before it happens.
pub fn model_cached() -> bool {
    std::fs::read_dir(cache_dir()).is_ok_and(|mut entries| entries.any(|e| e.is_ok()))
}

static MODEL_INSTANCE: OnceLock<Mutex<TextEmbedding>> = OnceLock::new();

fn model() -> Result<&'static Mutex<TextEmbedding>, String> {
    if let Some(model) = MODEL_INSTANCE.get() {
        return Ok(model);
    }
    let loaded = TextEmbedding::try_new(
        InitOptions::new(EmbeddingModel::ParaphraseMLMiniLML12V2Q)
            .with_cache_dir(cache_dir())
            .with_max_length(MAX_LENGTH)
            .with_show_download_progress(false),
    )
    .map_err(|e| format!("model unavailable ({e})"))?;
    Ok(MODEL_INSTANCE.get_or_init(|| Mutex::new(loaded)))
}

/// The vectors of some texts, in order. Blocking: the first call loads the
/// model (under a second, or a download the first time ever), then it is
/// a few milliseconds per text.
pub fn embed(texts: &[String]) -> Result<Vec<Vec<f32>>, String> {
    if texts.is_empty() {
        return Ok(Vec::new());
    }
    let model = model()?;
    let mut model = model.lock().map_err(|_| "model locked".to_string())?;
    let documents: Vec<&str> = texts.iter().map(String::as_str).collect();
    model.embed(documents, Some(32)).map_err(|e| format!("vectorization failed ({e})"))
}

fn index_path(dir: &Path) -> PathBuf {
    dir.join("vectors").join("vectors.jsonl")
}

/// The fingerprint of the text a vector was computed from, stored beside
/// it so regeneration can tell what actually moved (2026-09-21). The model
/// goes into it: change the model and every line is stale, which is right.
///
/// FNV-1a, 64 bits — dependency-free and stable for ever, which a hash
/// written into a versioned file must be. `DefaultHasher` is not: its
/// output is explicitly allowed to change between Rust releases.
fn digest(text: &str) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in MODEL.as_bytes().iter().chain(b"\0".iter()).chain(text.as_bytes().iter()) {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100_0000_01b3);
    }
    format!("{hash:016x}")
}

/// Which of these cards need the model run over them again: the ones with
/// no line yet, and the ones whose text no longer matches the fingerprint
/// stored beside their vector.
fn stale(slugs: &[&String], digests: &[String], known: &HashMap<String, (String, String)>) -> Vec<usize> {
    (0..slugs.len())
        .filter(|i| match known.get(slugs[*i]) {
            Some((stored, _)) => *stored != digests[*i],
            None => true,
        })
        .collect()
}

/// The index as it stands: slug → (fingerprint, the line itself, kept to
/// be written back byte for byte).
fn known_lines(path: &Path) -> HashMap<String, (String, String)> {
    let mut known = HashMap::new();
    let Ok(text) = std::fs::read_to_string(path) else { return known };
    for raw in text.lines().filter(|l| !l.trim().is_empty()) {
        if let Ok(parsed) = serde_json::from_str::<Line>(raw) {
            known.insert(parsed.slug, (parsed.h.unwrap_or_default(), raw.to_string()));
        }
    }
    known
}

/// One line of the index, in the shape the Python tool wrote — six
/// decimals, a diff-friendly order of keys.
fn line(slug: &str, digest: &str, vector: &[f32]) -> String {
    let values: Vec<String> = vector
        .iter()
        .map(|x| {
            let mut text = format!("{x:.6}");
            while text.ends_with('0') {
                text.pop();
            }
            if text.ends_with('.') {
                text.push('0');
            }
            text
        })
        .collect();
    format!("{{\"slug\": \"{slug}\", \"h\": \"{digest}\", \"v\": [{}]}}", values.join(", "))
}

#[derive(serde::Deserialize)]
struct Line {
    slug: String,
    /// Absent from indexes written before 2026-09-21: they regenerate once.
    #[serde(default)]
    h: Option<String>,
}

/// Put one vector into the index, in slug order, replacing the slug's line
/// if it has one. Returns the path written, for the commit.
pub fn write_vector(dir: &Path, slug: &str, text: &str, vector: &[f32]) -> Result<PathBuf, String> {
    let path = index_path(dir);
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let mut lines: Vec<(String, String)> = Vec::new();
    for text in existing.lines().filter(|l| !l.trim().is_empty()) {
        let parsed: Line = serde_json::from_str(text).map_err(|e| format!("vectors.jsonl unreadable ({e})"))?;
        if parsed.slug != slug {
            lines.push((parsed.slug, text.to_string()));
        }
    }
    lines.push((slug.to_string(), line(slug, &digest(text), vector)));
    lines.sort_by(|a, b| a.0.cmp(&b.0));
    write_index(&path, lines.iter().map(|(_, l)| l.as_str()))?;
    Ok(path)
}

fn write_index<'a>(path: &Path, lines: impl Iterator<Item = &'a str>) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("no vectors/ folder ({e})"))?;
    }
    let mut text = lines.collect::<Vec<_>>().join("\n");
    text.push('\n');
    std::fs::write(path, text).map_err(|e| format!("vectors.jsonl not written ({e})"))
}

/// The whole index, from every card — `forkstify vectors`. Replaces
/// `tools/vectoriser.py`; also writes `vectors/meta.toml`, which says what
/// produced the numbers. Returns how many cards were vectorized.
pub fn regenerate(dir: &Path, cards: &HashMap<String, Card>) -> Result<usize, String> {
    let mut slugs: Vec<&String> = cards.keys().collect();
    slugs.sort();
    // Composing the texts is cheap; running the model is not — and the
    // model is not reproducible to the last digit: regenerating everything
    // rewrote 358 lines out of 360 for nothing (2026-09-21). So keep every
    // line whose text has not moved, byte for byte, and run the model only
    // over the rest. A card's text carries its neighbours' links, so a new
    // link does make both sides stale, as it should.
    let path = index_path(dir);
    let known = known_lines(&path);
    let texts: Vec<String> = slugs.iter().map(|slug| text_of(slug, &cards[*slug], cards)).collect();
    let digests: Vec<String> = texts.iter().map(|text| digest(text)).collect();
    let todo = stale(&slugs, &digests, &known);

    let mut computed: HashMap<usize, String> = HashMap::new();
    if !todo.is_empty() {
        let fresh: Vec<String> = todo.iter().map(|i| texts[*i].clone()).collect();
        let vectors = embed(&fresh)?;
        if vectors.len() != todo.len() {
            return Err(format!("the model returned {} vectors for {} texts", vectors.len(), todo.len()));
        }
        for (vector, i) in vectors.iter().zip(&todo) {
            computed.insert(*i, line(slugs[*i], &digests[*i], vector));
        }
    }
    let lines: Vec<String> = (0..slugs.len())
        .map(|i| match computed.remove(&i) {
            Some(fresh) => fresh,
            // unchanged: the line we already had, to the byte
            None => known[slugs[i]].1.clone(),
        })
        .collect();
    write_index(&index_path(dir), lines.iter().map(String::as_str))?;
    let meta = format!(
        "model = \"{MODEL}\"\ndimensions = {DIMENSIONS}\npooling = \"mean\"\nmax_length = {MAX_LENGTH}\nnormalized = true\ncards = {}\n",
        slugs.len()
    );
    std::fs::write(dir.join("vectors").join("meta.toml"), meta).map_err(|e| format!("meta.toml not written ({e})"))?;
    Ok(slugs.len())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The fingerprint is what tells a current line from a stale one, so it
    /// must depend on the text and on nothing else that drifts.
    #[test]
    fn the_fingerprint_follows_the_text() {
        let one = digest("The Cure. Genres : post-punk");
        assert_eq!(one, digest("The Cure. Genres : post-punk"), "same text, same fingerprint");
        assert_ne!(one, digest("The Cure. Genres : post-punk, 80s"), "a word more, another fingerprint");
        assert_eq!(one.len(), 16, "sixteen hex characters");
        assert!(one.chars().all(|c| c.is_ascii_hexdigit()));
    }

    /// 2026-09-21: only what moved goes back through the model. An index
    /// written before the fingerprints has none, so it regenerates once.
    #[test]
    fn only_the_cards_whose_text_moved_are_recomputed() {
        let (a, b, c) = ("air".to_string(), "blur".to_string(), "cure".to_string());
        let slugs = vec![&a, &b, &c];
        let digests = vec![digest("air"), digest("blur"), digest("cure")];
        let known: HashMap<String, (String, String)> = HashMap::from([
            // unchanged
            (a.clone(), (digest("air"), "{\"slug\": \"air\"}".to_string())),
            // its text moved
            (b.clone(), (digest("blur, once"), "{\"slug\": \"blur\"}".to_string())),
            // 'cure' has no line at all
        ]);
        assert_eq!(stale(&slugs, &digests, &known), vec![1, 2]);

        // an index with no fingerprints: everything is stale, once
        let old: HashMap<String, (String, String)> =
            HashMap::from([(a.clone(), (String::new(), String::new()))]);
        assert_eq!(stale(&slugs, &digests, &old), vec![0, 1, 2]);
    }

    fn card(text: &str) -> Card {
        toml::from_str(text).unwrap()
    }

    fn two_cards() -> HashMap<String, Card> {
        let mut cards = HashMap::new();
        cards.insert(
            "the-cure".to_string(),
            card("name = \"The Cure\"\nbegin = \"1976-05\"\norigin = \"Crawley\"\ntags = [\"post-punk\", \"uk\", \"80s\"]\nlinks = [{ to = \"siouxsie-and-the-banshees\", type = \"scene\" }, { to = \"nobody\", type = \"similar\" }]\ndescription = \" Gothique et pop. \"\n"),
        );
        cards.insert(
            "siouxsie-and-the-banshees".to_string(),
            card("name = \"Siouxsie and the Banshees\"\nbegin = \"1976\"\nend = \"1996\"\ntags = [\"post-punk\", \"gb\", \"1970s\"]\nlinks = [{ to = \"the-cure\", type = \"influence\" }]\n"),
        );
        cards
    }

    /// Word for word what `tools/vectoriser.py --textes` composed: same
    /// sentences, same order, links both ways, the dangling one dropped —
    /// down to the double period after a description that ends with one
    /// (checked on the 316 texts of the reference, 09/09/2026).
    #[test]
    fn the_text_is_the_python_one() {
        let cards = two_cards();
        assert_eq!(
            text_of("the-cure", &cards["the-cure"], &cards),
            "The Cure. Genres : post punk. Pays : Royaume-Uni. Époque : années 1980. Actif depuis 1976. Origine : Crawley. même scène que Siouxsie and the Banshees ; a influencé Siouxsie and the Banshees. Gothique et pop.."
        );
        assert_eq!(
            text_of("siouxsie-and-the-banshees", &cards["siouxsie-and-the-banshees"], &cards),
            "Siouxsie and the Banshees. Genres : post punk. Pays : GB. Époque : années 1970. Actif de 1976 à 1996. influencé par The Cure ; même scène que The Cure."
        );
    }

    /// The index stays sorted by slug and a slug has one line only.
    #[test]
    fn a_vector_lands_in_slug_order_and_replaces_its_own() {
        let dir = std::env::temp_dir().join(format!("forkstify-embed-{}", std::process::id()));
        std::fs::create_dir_all(dir.join("vectors")).unwrap();
        write_vector(&dir, "pulp", "Pulp", &[0.5, -0.25]).unwrap();
        write_vector(&dir, "air", "Air", &[0.1, 0.0]).unwrap();
        write_vector(&dir, "pulp", "Pulp", &[0.123456789, 1.0]).unwrap();
        let text = std::fs::read_to_string(index_path(&dir)).unwrap();
        assert_eq!(
            text,
            format!(
                "{{\"slug\": \"air\", \"h\": \"{}\", \"v\": [0.1, 0.0]}}\n{{\"slug\": \"pulp\", \"h\": \"{}\", \"v\": [0.123457, 1.0]}}\n",
                digest("Air"),
                digest("Pulp")
            )
        );
        std::fs::remove_dir_all(dir).unwrap();
    }
}
